import { SVGIcon } from "./pages/shared/models/icons/icon-model";

export const appIcons: SVGIcon[] = [
  { iconName: "location", iconAsset: "assets/icons/location.svg" },
  { iconName: "email", iconAsset: "assets/icons/email.svg" },
  { iconName: "phone", iconAsset: "assets/icons/phone.svg" },
  { iconName: "clear", iconAsset: "assets/icons/clear.svg" },
  { iconName: "settings", iconAsset: "assets/icons/settings.svg" },
  { iconName: "expand-more", iconAsset: "assets/icons/expand_more.svg" },
  { iconName: "expand-less", iconAsset: "assets/icons/expand_less.svg" },
  {
    iconName: "machine-learning",
    iconAsset: "assets/icons/machine-learning.svg",
  },
  {
    iconName: "computer-vision",
    iconAsset: "assets/icons/computer-vision.svg",
  },
  { iconName: "nlp", iconAsset: "assets/icons/nlp.svg" },
  { iconName: "ai-solution", iconAsset: "assets/icons/ai-solution.svg" },
  { iconName: "ai-integration", iconAsset: "assets/icons/ai-integration.svg" },
  { iconName: "light-bulb", iconAsset: "assets/icons/light-bulb.svg" },
  { iconName: "measuring-tape", iconAsset: "assets/icons/measuring-tape.svg" },
  { iconName: "shield", iconAsset: "assets/icons/shield.svg" },
  { iconName: "chart-upward", iconAsset: "assets/icons/chart-upward.svg" },
  { iconName: "rocket", iconAsset: "assets/icons/rocket.svg" },
  { iconName: "web", iconAsset: "assets/icons/web.svg" },
  { iconName: "mobile", iconAsset: "assets/icons/mobile.svg" },
  { iconName: "cloud", iconAsset: "assets/icons/cloud.svg" },
  { iconName: "menu-mobile", iconAsset: "assets/icons/menu-mobile.svg" },
  { iconName: "iaas", iconAsset: "assets/icons/iaas.svg" },
  { iconName: "paas", iconAsset: "assets/icons/paas.svg" },
  { iconName: "cloud-strategy", iconAsset: "assets/icons/cloud-strategy.svg" },
  { iconName: "cloud_main", iconAsset: "assets/icons/cloud_main.svg" },
  { iconName: "cloud-security", iconAsset: "assets/icons/cloud-security.svg" },
  { iconName: "handshake", iconAsset: "assets/icons/handshake.svg" },
  {
    iconName: "data-management",
    iconAsset: "assets/icons/data-management.svg",
  },
  { iconName: "facebook", iconAsset: "assets/icons/fcb-new.svg" },
  { iconName: "linkedin", iconAsset: "assets/icons/linkedin-new.svg" },
];
